# After changing this file, verify the syntax on http://lint.travis-ci.org/
language: python
python:
    - "3.6"
env:
  global:
      - PYTHONPATH=${PYTHONPATH}:src

install:
- pip install -r requirements.txt

script: pytest
